title: Vladimir Zhdanov
subtitle: EHP E-Portfolio
description: Site of Vladimir Zhdanov's EHP E-Portfolio
author: Vladimir Zhdanov
email: vladimir.zhdanov@colorado.edu
twitter_url: "http://twitter.com/vladzhdanov/"

avatar: assets/images/avatar.jpg
remote_theme : chrisbobbe/jekyll-theme-prologue
collections: [sections]
